name: Build docker images
on:
  push:
    paths:
      - 'instructor-client/**'
      - 'server/**'
      - 'cicd/**'
      - 'nginx/**'
    branches:
      - main
  workflow_dispatch:
  workflow_call:
jobs:
  build-server-image:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and set image tag
        run: |
          if test "${{ github.ref_name }}" = "main"; then 
            export tag=":stable"; 
          elif test "${{ github.ref_name }}" = "develop"; then 
            export tag=":dev";
          elif echo "${{ github.ref_name }}" | grep -q "^release/"; then
            export tag=$(echo "${{ github.ref_name }}" | sed "s/release\///");
          elif echo "${{ github.ref_name }}" | grep -q "^rc/"; then
            export tag=$(echo "${{ github.ref_name }}" | sed "s/rc\///")-rc;
          else 
            export tag="";
          fi
          echo "IMAGE_TAG=${tag}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/src/main/docker/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/franklyn-server${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-instructor-client-image:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and set image tag
        run: |
          if test "${{ github.ref_name }}" = "main"; then 
            export tag=":stable"; 
          elif test "${{ github.ref_name }}" = "develop"; then 
            export tag=":dev";
          elif echo "${{ github.ref_name }}" | grep -q "^release/"; then
            export tag=$(echo "${{ github.ref_name }}" | sed "s/release\///");
          elif echo "${{ github.ref_name }}" | grep -q "^rc/"; then
            export tag=$(echo "${{ github.ref_name }}" | sed "s/rc\///")-rc;
          else 
            export tag="";
          fi
          echo "IMAGE_TAG=${tag}" >> "$GITHUB_ENV"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'instructor-client/package-lock.json'

      - name: Build instructor-client
        run: |
          ./cicd/build-instructor-client.sh

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./instructor-client/docker/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/franklyn-instructor-client${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max